<?php

define(
    "PATH_PROJECT_ROOT",
    dirname(dirname(dirname(dirname(__DIR__))))
);
define("PATH_BACKEND", PATH_PROJECT_ROOT.DIRECTORY_SEPARATOR.'backEnd');
define("PATH_ROOT", PATH_BACKEND.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Main');
define(
    "PATH_CONFIG",
    PATH_ROOT.
    DIRECTORY_SEPARATOR.'Core'.
    DIRECTORY_SEPARATOR.'config'
);
define("PATH_LANGS", PATH_ROOT.DIRECTORY_SEPARATOR.'Lang');
define("PATH_PUBLIC", PATH_PROJECT_ROOT.DIRECTORY_SEPARATOR.'web');
